version: "3.8"
services:
  bulletin-board-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: board
      POSTGRES_PASSWORD: board
      POSTGRES_DB: board
    restart: always
    networks:
      - lesson
networks:
  lesson:
